# Generated by Django 2.0.8 on 2018-10-18 22:25

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('assist', '0002_auto_20181008_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='section',
            name='published_date',
        ),
        migrations.AlterField(
            model_name='section',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
