# Generated by Django 2.0.8 on 2018-10-18 22:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assist', '0003_auto_20181018_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='section',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
