# Generated by Django 2.0.8 on 2018-10-18 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assist', '0004_auto_20181018_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='section',
            name='published_date',
        ),
    ]
